spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/archon_open_metadata
    username: adsuser
    password: AdS@3421
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

app:
  cors:
    allow-credentials: false
    allowed-origins: "*"
    allowed-headers: "*"
    allowed-methods: "*"
    path-pattern: "/**"
