spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/metadata_engine
spring.datasource.username=adsuser
spring.datasource.password=AdS@3421
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.web.cors.allowed-origins=*

# Silence SchemaCrawler verbose telemetry loop noise
logging.level.us.fatehi=OFF
